// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEntity = `-- name: GetEntity :one
SELECT id, tenant_id, ext_id, label, type_uri, description, embedding, meta, created_at, updated_at
FROM entities
WHERE id = $1
`

func (q *Queries) GetEntity(ctx context.Context, id pgtype.UUID) (Entity, error) {
	row := q.db.QueryRow(ctx, getEntity, id)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ExtID,
		&i.Label,
		&i.TypeUri,
		&i.Description,
		&i.Embedding,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEntitiesByTenant = `-- name: ListEntitiesByTenant :many
SELECT id, tenant_id, ext_id, label, type_uri, description, embedding, meta, created_at, updated_at
FROM entities
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListEntitiesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Entity, error) {
	rows, err := q.db.Query(ctx, listEntitiesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entity
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ExtID,
			&i.Label,
			&i.TypeUri,
			&i.Description,
			&i.Embedding,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
