// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Dossier struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	AssembledAt pgtype.Timestamptz `json:"assembled_at"`
	Bundle      []byte             `json:"bundle"`
}

type Entity struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ExtID       pgtype.Text        `json:"ext_id"`
	Label       string             `json:"label"`
	TypeUri     pgtype.Text        `json:"type_uri"`
	Description pgtype.Text        `json:"description"`
	Embedding   pgvector.Vector    `json:"embedding"`
	Meta        []byte             `json:"meta"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Property struct {
	ID          pgtype.UUID `json:"id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	Slug        string      `json:"slug"`
	Label       string      `json:"label"`
	ValueType   string      `json:"value_type"`
	Description pgtype.Text `json:"description"`
}

type ProposedProperty struct {
	ID                pgtype.UUID        `json:"id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	ProposedSlug      string             `json:"proposed_slug"`
	ProposedValueType string             `json:"proposed_value_type"`
	ProposedBy        string             `json:"proposed_by"`
	ExampleExcerpt    pgtype.Text        `json:"example_excerpt"`
	ExampleSourceID   pgtype.UUID        `json:"example_source_id"`
	Status            string             `json:"status"`
	ReviewedBy        pgtype.Text        `json:"reviewed_by"`
	ReviewedAt        pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Qualifier struct {
	ID          pgtype.UUID        `json:"id"`
	StatementID pgtype.UUID        `json:"statement_id"`
	PropertyID  pgtype.UUID        `json:"property_id"`
	ValText     pgtype.Text        `json:"val_text"`
	ValNumber   pgtype.Numeric     `json:"val_number"`
	ValDate     pgtype.Timestamptz `json:"val_date"`
	ValEntity   pgtype.UUID        `json:"val_entity"`
}

type Relation struct {
	ID          pgtype.UUID     `json:"id"`
	TenantID    pgtype.UUID     `json:"tenant_id"`
	SourceID    pgtype.UUID     `json:"source_id"`
	TargetID    pgtype.UUID     `json:"target_id"`
	Type        string          `json:"type"`
	Weight      pgtype.Numeric  `json:"weight"`
	Confidence  pgtype.Numeric  `json:"confidence"`
	Description pgtype.Text     `json:"description"`
	Embedding   pgvector.Vector `json:"embedding"`
	Meta        []byte          `json:"meta"`
	StatementID pgtype.UUID     `json:"statement_id"`
}

type Source struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Url            string             `json:"url"`
	FetchedAt      pgtype.Timestamptz `json:"fetched_at"`
	ContentHash    string             `json:"content_hash"`
	RawHtml        []byte             `json:"raw_html"`
	RawText        pgtype.Text        `json:"raw_text"`
	ArchiveUrl     pgtype.Text        `json:"archive_url"`
	Publisher      pgtype.Text        `json:"publisher"`
	Title          pgtype.Text        `json:"title"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	Embedding      pgvector.Vector    `json:"embedding"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SourceVerification struct {
	ID             pgtype.UUID        `json:"id"`
	SourceID       pgtype.UUID        `json:"source_id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	VerifiedAt     pgtype.Timestamptz `json:"verified_at"`
	Status         string             `json:"status"`
	NewContentHash pgtype.Text        `json:"new_content_hash"`
	Notes          pgtype.Text        `json:"notes"`
}

type Statement struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	SubjectID  pgtype.UUID        `json:"subject_id"`
	PropertyID pgtype.UUID        `json:"property_id"`
	ValEntity  pgtype.UUID        `json:"val_entity"`
	ValText    pgtype.Text        `json:"val_text"`
	ValNumber  pgtype.Numeric     `json:"val_number"`
	ValDate    pgtype.Timestamptz `json:"val_date"`
	ValJson    []byte             `json:"val_json"`
	Rank       string             `json:"rank"`
	Confidence pgtype.Numeric     `json:"confidence"`
	Embedding  pgvector.Vector    `json:"embedding"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type StatementSource struct {
	ID                 pgtype.UUID        `json:"id"`
	StatementID        pgtype.UUID        `json:"statement_id"`
	SourceID           pgtype.UUID        `json:"source_id"`
	Excerpt            string             `json:"excerpt"`
	ExcerptOffsetStart int32              `json:"excerpt_offset_start"`
	ExcerptOffsetEnd   int32              `json:"excerpt_offset_end"`
	ExtractionMethod   string             `json:"extraction_method"`
	ExtractedAt        pgtype.Timestamptz `json:"extracted_at"`
	Confidence         pgtype.Numeric     `json:"confidence"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
}

type VConflict struct {
	StatementAID pgtype.UUID        `json:"statement_a_id"`
	StatementBID pgtype.UUID        `json:"statement_b_id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	SubjectID    pgtype.UUID        `json:"subject_id"`
	PropertyID   pgtype.UUID        `json:"property_id"`
	PropertySlug string             `json:"property_slug"`
	ValAText     pgtype.Text        `json:"val_a_text"`
	ValANumber   pgtype.Numeric     `json:"val_a_number"`
	ValADate     pgtype.Timestamptz `json:"val_a_date"`
	ValAEntity   pgtype.UUID        `json:"val_a_entity"`
	ValBText     pgtype.Text        `json:"val_b_text"`
	ValBNumber   pgtype.Numeric     `json:"val_b_number"`
	ValBDate     pgtype.Timestamptz `json:"val_b_date"`
	ValBEntity   pgtype.UUID        `json:"val_b_entity"`
	ConfidenceA  pgtype.Numeric     `json:"confidence_a"`
	ConfidenceB  pgtype.Numeric     `json:"confidence_b"`
	RankA        string             `json:"rank_a"`
	RankB        string             `json:"rank_b"`
	CreatedA     pgtype.Timestamptz `json:"created_a"`
	CreatedB     pgtype.Timestamptz `json:"created_b"`
}
