// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: properties.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPropertiesByTenant = `-- name: ListPropertiesByTenant :many
SELECT id, tenant_id, slug, label, value_type, description
FROM properties
WHERE tenant_id = $1 OR tenant_id IS NULL
ORDER BY slug
`

func (q *Queries) ListPropertiesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Property, error) {
	rows, err := q.db.Query(ctx, listPropertiesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Property
	for rows.Next() {
		var i Property
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Label,
			&i.ValueType,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
