// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qualifiers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listQualifiersByStatement = `-- name: ListQualifiersByStatement :many
SELECT id, statement_id, property_id, val_text, val_number, val_date, val_entity
FROM qualifiers
WHERE statement_id = $1
`

func (q *Queries) ListQualifiersByStatement(ctx context.Context, statementID pgtype.UUID) ([]Qualifier, error) {
	rows, err := q.db.Query(ctx, listQualifiersByStatement, statementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Qualifier
	for rows.Next() {
		var i Qualifier
		if err := rows.Scan(
			&i.ID,
			&i.StatementID,
			&i.PropertyID,
			&i.ValText,
			&i.ValNumber,
			&i.ValDate,
			&i.ValEntity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
