// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetEntity(ctx context.Context, id pgtype.UUID) (Entity, error)
	ListEntitiesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Entity, error)
	ListPropertiesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Property, error)
	ListQualifiersByStatement(ctx context.Context, statementID pgtype.UUID) ([]Qualifier, error)
	ListSourcesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Source, error)
	ListStatementsBySubject(ctx context.Context, subjectID pgtype.UUID) ([]Statement, error)
}

var _ Querier = (*Queries)(nil)
