// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listSourcesByTenant = `-- name: ListSourcesByTenant :many
SELECT id, tenant_id, url, fetched_at, content_hash, raw_html, raw_text, archive_url, publisher, title, published_at, embedding, last_verified_at, status, created_at, meta
FROM sources
WHERE tenant_id = $1
ORDER BY fetched_at DESC
`

func (q *Queries) ListSourcesByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Source, error) {
	rows, err := q.db.Query(ctx, listSourcesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Source
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Url,
			&i.FetchedAt,
			&i.ContentHash,
			&i.RawHtml,
			&i.RawText,
			&i.ArchiveUrl,
			&i.Publisher,
			&i.Title,
			&i.PublishedAt,
			&i.Embedding,
			&i.LastVerifiedAt,
			&i.Status,
			&i.CreatedAt,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
