// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statements.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listStatementsBySubject = `-- name: ListStatementsBySubject :many
SELECT id, tenant_id, subject_id, property_id, val_entity, val_text, val_number, val_date, val_json, rank, confidence, embedding, created_at
FROM statements
WHERE subject_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListStatementsBySubject(ctx context.Context, subjectID pgtype.UUID) ([]Statement, error) {
	rows, err := q.db.Query(ctx, listStatementsBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Statement
	for rows.Next() {
		var i Statement
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubjectID,
			&i.PropertyID,
			&i.ValEntity,
			&i.ValText,
			&i.ValNumber,
			&i.ValDate,
			&i.ValJson,
			&i.Rank,
			&i.Confidence,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
